Mufaro frontend
sarahrittgers26/sps-2021-team-18 pull request #16
Opened 2021-04-05 04:26 UTC by MufaroMakiwa

2021-04-05 08:49 UTC, michaellawes approved these changes

2021-04-05 13:51 UTC, cenofe approved these changes

2021-04-05 15:04 UTC, sarahrittgers26 requested changes
Please remove temporary files. Also, please remember to add semicolons at the ends of lines, it's good style (https://google.github.io/styleguide/jsguide.html#formatting-semicolons-are-required)

Also, are files with META-INF necessary? They seem to be copies of other files

2021-04-05 15:04 UTC, sarahrittgers26 commented on src/main/webapp/App.js
> +        <Route path="/projects" exact component={Projects} /> */}
Are these still needed? Can we remove them if not?

2021-04-05 15:04 UTC, sarahrittgers26 commented on src/main/webapp/components/Projects/ConnectionDialog.js
> +          <span className="ConnectionDialog_summary">{`Waiting for ${collaborator} to connect...`}</span>
nit: can we format this with the text content on a new line so it's easier to read

```
<span ...>
    {`Text content`}
</span>
```

2021-04-05 15:04 UTC, sarahrittgers26 commented on src/main/webapp/components/Projects/Projects.js
> +import React, {useEffect, useState, useRef} from 'react'
nit: put useRef before useState, to keep it in order

2021-04-05 15:04 UTC, sarahrittgers26 commented on src/main/webapp/components/Projects/Searchbar.js
> +  }, [focus]);
let's fix the formatting to follow the style guide https://eslint.org/docs/rules/multiline-ternary

```
useEffect(
    () => {
        focus ?
            searchBarRef.current.classList.add('Searchbar_container_focused') :
            searchBarRef.current.classList.remove(
                'Searchbar_container_focused')},
    [focus]);
```

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/App.js
> +        <Route path="/projects" exact component={Projects} /> */}
remove if not needed?

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/App.js
> +});
let's put the constants at the top together. and exports at the bottom

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Editor/Editor.js
> +  }, [html, css, js])
nits: add semicolons on lines 23 and 26

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Editor/Editor.js
> +  )
nit: add a semicolon

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Editor/Navbar.js
> +  )
nit: add a semicolon

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Editor/Pane.js
> +  )
add semicolon

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/AspectRatio.js
> +  )
please add semicolons at the ends of lines

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/ConnectionDialog.js
> +          <span className="ConnectionDialog_summary">{`Waiting for ${collaborator} to connect...`}</span>
please fix the indentation

```
<span className="ConnectionDialog_summary">
    {`Waiting for ${collaborator} to connect...`}
</span>
```

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/Header.js
> +  }
add semicolons, here and below

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/Header.js
> +        if (displayMenu) {
why can't this if statement be included above? since there's no else here

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/Header.js
> +  }, [displayMenu])
missing semicolon

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/Header.js
> +        <div className="Header_user_icon" ref={iconRef} onClick={() => setDisplayMenu(prevState => !prevState)}></div>
```
<div className="Header_user_icon" 
     ref={iconRef} 
     onClick={() => setDisplayMenu(prevState => !prevState)}>
</div>
```

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/ProjectCard.js
> +  )
semicolon

2021-04-05 15:04 UTC, sarahrittgers26 commented on target/classes/META-INF/resources/components/Projects/Projects.js
> +]
add semicolons, here and below

2021-04-05 16:46 UTC, MufaroMakiwa commented on src/main/webapp/App.js
> +        <Route path="/projects" exact component={Projects} /> */}
Yes we still need them. I just commented them for quick testing and forgot to uncomment them afterwards.

2021-04-05 16:51 UTC, MufaroMakiwa commented on src/main/webapp/components/Projects/ConnectionDialog.js
> +          <span className="ConnectionDialog_summary">{`Waiting for ${collaborator} to connect...`}</span>
Okay sure. I have updated all the spans to have the same format

2021-04-05 16:53 UTC, MufaroMakiwa commented on src/main/webapp/components/Projects/Projects.js
> +import React, {useEffect, useState, useRef} from 'react'
Does this mean that the order for adding react hooks has to follow this order:

useEffect, useRef, useState

2021-04-05 17:49 UTC, sarahrittgers26 commented on src/main/webapp/components/Projects/Projects.js
> +import React, {useEffect, useState, useRef} from 'react'
no, this is just for good style to have them alphabetized

2021-04-05 21:54 UTC, MufaroMakiwa commented on src/main/webapp/components/Projects/Projects.js
> +import React, {useEffect, useState, useRef} from 'react'
Okay thats great

2021-04-05 21:55 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/App.js
> +        <Route path="/projects" exact component={Projects} /> */}
We are still trying to add those files to gitignore because they keep on getting generated and being added to the repo

2021-04-05 21:56 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Editor/Editor.js
> +  }, [html, css, js])
Updated

2021-04-05 21:57 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Editor/Editor.js
> +  )
Noted.

2021-04-05 21:57 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Editor/Navbar.js
> +  )
Noted

2021-04-05 21:59 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Editor/Pane.js
> +  )
Noted

2021-04-05 21:59 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Projects/AspectRatio.js
> +  )
Noted

2021-04-05 22:01 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Projects/Header.js
> +        <div className="Header_user_icon" ref={iconRef} onClick={() => setDisplayMenu(prevState => !prevState)}></div>
Updated

2021-04-05 22:01 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Projects/ProjectCard.js
> +  )
Noted

2021-04-05 22:01 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Projects/Projects.js
> +]
Noted

2021-04-05 22:01 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/App.js
> +});
Noted

2021-04-05 22:01 UTC, MufaroMakiwa commented on src/main/webapp/components/Projects/Searchbar.js
> +  }, [focus]);
Noted

2021-04-05 23:05 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Projects/Header.js
> +  }, [displayMenu])
Noted

2021-04-05 23:05 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Projects/Header.js
> +        if (displayMenu) {
Updated

2021-04-05 23:06 UTC, MufaroMakiwa commented on target/classes/META-INF/resources/components/Projects/Header.js
> +  }
Updated

2021-04-06 02:07 UTC, sarahrittgers26 approved these changes

2021-04-06 02:36 UTC, andiov approved these changes

2021-04-06 02:55 UTC, merged